# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/config.ini', 'config'),
        ('resources/logo.ico', 'resources'),
        ('resources/logo.png', 'resources'),
        ('file_version_info.txt', '.'),
    ],
    hiddenimports=[
        'google.cloud.vision_v1',
        'google.cloud.translate_v2',
        'PyQt5.QtWidgets',
        'PyQt5.QtGui',
        'PyQt5.QtCore',
        'PIL.Image',
        'PIL._tkinter_finder',
        'PIL._imaging',
        'pyscreeze',
        'socket',
        'http.client',
        'urllib.request',
        'urllib.parse',
        'ssl',
        'pkg_resources',
        'setuptools',
        'pytesseract',
        'customtkinter',
        'darkdetect',
        'numpy',
        'cv2',
        'pyautogui',
        'screeninfo',
        'configparser',
        'logging',
        'json',
        'threading',
        'concurrent.futures',
        'collections',
        'enum',
        'typing',
        'datetime',
        'hashlib',
        'functools',
        'platform',
        'requests',
        'html',
        'secrets'
    ],
    hookspath=['.'],  # Include custom hook-PyQt5.py
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'sqlite3', 'pydoc', 'test', '__main__',
        'multiprocessing', 'ftplib', 'netrc', 'xmlrpc', 'unittest', 'curses', '_pyrepl',
        'PyQt5.QtPrintSupport', 'PyQt5.QtBluetooth', 'PyQt5.QtDesigner', 'PyQt5.QtMultimedia',
        'PyQt5.QtNetwork', 'PyQt5.QtOpenGL', 'PyQt5.QtSql', 'PyQt5.QtTest', 'PyQt5.QtWebEngine',
        'google.cloud.storage', 'google.cloud.bigquery', 'google.cloud.pubsub',
        'google.cloud.datastore', 'google.cloud.firestore', 'google.cloud.spanner',
        'google.cloud.bigtable', 'google.cloud.redis', 'google.cloud.memcache',
        'google.cloud.tasks', 'google.cloud.scheduler', 'google.cloud.monitoring',
        'google.cloud.logging', 'google.cloud.error_reporting', 'google.cloud.trace',
        'google.cloud.profiler', 'google.cloud.debugger', 'google.cloud.testing',
        'google.cloud.resource_manager', 'google.cloud.iam', 'google.cloud.kms',
        'google.cloud.secret_manager', 'google.cloud.security_center',
        'google.cloud.websecurityscanner', 'google.cloud.recaptcha_enterprise',
        'google.cloud.dlp', 'google.cloud.asset', 'google.cloud.orgpolicy',
        'google.cloud.access_approval', 'google.cloud.access_context_manager',
        'google.cloud.osconfig', 'google.cloud.oslogin', 'google.cloud.compute',
        'google.cloud.appengine', 'google.cloud.cloudfunctions', 'google.cloud.run',
        'google.cloud.workflows', 'google.cloud.scheduler', 'google.cloud.tasks',
        'google.cloud.iot', 'google.cloud.iot_v1', 'google.cloud.iot_v2',
        'google.cloud.iot_core', 'google.cloud.iot_core_v1', 'google.cloud.iot_core_v2',
        'google.cloud.iot_core_v3', 'google.cloud.iot_core_v4', 'google.cloud.iot_core_v5',
        'google.cloud.iot_core_v6', 'google.cloud.iot_core_v7', 'google.cloud.iot_core_v8',
        'google.cloud.iot_core_v9', 'google.cloud.iot_core_v10'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DainnScreenTranslator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=['Qt5Core.dll', 'Qt5Gui.dll', 'Qt5Widgets.dll', 'python3*.dll'],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='file_version_info.txt',
    icon='resources\\logo.ico',
    uac_admin=False,
    onefile=True,
    optimize=2,
    bundle_files=1,
    compressed=True,
)